version: '3.7'

services:

  graphdb:
    image: graphdb
    container_name: graphdb
    ports:
      - "7200:7200"
    volumes:
      - ./data:/opt/graphdb/home

  frontback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontback
    ports:
      - "8501:8501"
    env_file:
      - .env
